features:
  logo: 0
  name: 1
  slogan: 1
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
  path: 'public://hurr3.jpg'
favicon:
  use_default: 1
  path: ''
